### ISSUE TITLE
Lidar PointCloud flipped upside down

### ISSUE THREAD

**Issue by Roosstef** [carla-simulator/ros-bridge#268]
Hi all,

since the newest update on Carla 0.9.9 the Lidar Pointcloud ist flipped upside down using the carla_ros_bridge. 

(See attached image)
![Screenshot from 2020-04-29 11-18-38](https://user-images.githubusercontent.com/43417803/80580050-3bc10400-8a0b-11ea-9015-e399b500eb84.png)

Using the Carla_ad_demo the Ground-Truth marker is flipped upside down and the PC is alligned correctly. [EDIT] Because the fixed frame is set to map. (See here)
![Screenshot from 2020-04-29 11-22-41](https://user-images.githubusercontent.com/43417803/80580413-c7d32b80-8a0b-11ea-9d15-cc70ca89b376.png)

Is anyone else aware of this issue?

**Comment by fpasch** [comment]
Could you please verify with the latest master?

**Comment by Roosstef** [comment]
Hi @fpasch,

The NPC Markers are visible now! And the point cloud see to be flipped correctly when in frame "map". But my robot model is flipped upside down.

![Carla_issue](https://user-images.githubusercontent.com/43417803/80965130-57b11500-8e12-11ea-9086-49ddf31aa95b.png)

When im in frame "ego_vehicle" the PC and the Markers are flipped.
![Carla_Issue2](https://user-images.githubusercontent.com/43417803/80965322-9a72ed00-8e12-11ea-856d-a712a0023eb1.png)

Thank you for your help.

Greetings 
Stefan

**Comment by Roosstef** [comment]
Are there any plans to fix this issue?

**Comment by fabianoboril** [comment]
There was an issue with the TF of the ego vehicle, which we just fixed. Could you check the TFs on your side, whether you see any abnormalities? Thank you.

**Comment by Roosstef** [comment]
Hey @fabianoboril, there is an issue with the ego_vehicle TF (TF is also flipped upside down.)
How did you fixed this problem? This is a carla_ros_bridge issue right? 
Greetings
Stefan

**Comment by fabianoboril** [comment]
@Roosstef We merge a fix today #299 for the ego_vehicle TF.

**Comment by Roosstef** [comment]
Ok my bad I missed that :)
Thank you!

**Comment by vedthakur5** [comment]
@Roosstef How did you set the lidar data on rviz. Can you explain all the steps in brief. My lidar data is not being visible in the rviz

**Comment by Roosstef** [comment]
Just Start a Carla Server and run the carla_ad_demo.launch.

**Comment by vedthakur5** [comment]
Is it ok to run carla_ad_demo_with_rviz.launch
and  check my lidar sensor:

{
            "type": "sensor.lidar.ray_cast",
            "id": "lidar1",
            "x": 0.0, "y": 0.0, "z": 2.4, "roll": 0.0, "pitch": 0.0, "yaw": 0.0,
            "range": 50,
            "channels": 32,
            "points_per_second": 320000,
            "upper_fov": 2.0,
            "lower_fov": -26.8,
            "rotation_frequency": 20,
            "sensor_tick": 0.0
        },
and what does pointcloud2 "marker" mean.....I know only pointcloud2 which is one of the options in "Add" in Rviz

Please mention the topic of this pointcloud2 also
Thanks for your reply...

**Comment by vedthakur5** [comment]
Thanks bro...I solved it myself
Actually in the official carla-ros-bridge pkg the topic for pointcloud2 is:
/carla/ego_vehicle/lidar/front/point_cloud
but since from the below lidar sensor in sensors.json file in carla_ego_vehicle/ config

{
"type": "sensor.lidar.ray_cast",
"id": "lidar1",
"x": 0.0, "y": 0.0, "z": 2.4, "roll": 0.0, "pitch": 0.0, "yaw": 0.0,
"range": 50,
"channels": 32,
"points_per_second": 320000,
"upper_fov": 2.0,
"lower_fov": -26.8,
"rotation_frequency": 20,
"sensor_tick": 0.0
},

we see that the id is lidar1 so the topic for pointcloud2 should be
/carla/ego_vehicle/lidar/lidar1/point_cloud
-----------------------------------------------------------------------------------------------
It's better that the creators change it in official carla-ros-bridge pkg
