### ISSUE TITLE
rospy.service.ServiceException: service [/carla/ego_vehicle/set_parameters] already registered

### ISSUE THREAD

**Issue by krdindorkar19** [carla-simulator/ros-bridge#35]

**Comment by fabianoboril** [comment]
Are you using two ego vehicles? For each you need to run a separate ros-bridge!

**Comment by krdindorkar19** [comment]
No, steps I am following are : 
1. Running server in Terminal 1
2. Running : roslaunch carla_ros_bridge client_with_rviz.launch rosbag_fname:=bag_file_name.bag in Terminal 2
3. Running : python single_vehicle_example.py  from feature/example branch in Terminal 3
Even if I am running with manual_control.py, its giving me same error

**Comment by krdindorkar19** [comment]
@fabianoboril , It is conflicting between the vehicle I have created in manual_control and one from setting.YAML file, how to map vehicle from setting.YAML file to manual_control.py?

**Comment by rohanb2018** [comment]
Running into the same issue when I was trying to run `manual_control.py` with `client_with_rviz.launch`, but only when the `control_mode` is set to `ackermann` (it seemed to work fine with the mode set to `pedal`, probably because the pedal controller doesn't use a dynamic reconfigure server). This was on the 0.9.2 ROS bridge version, though, so maybe the issue is resolved now?

**Comment by fpasch** [comment]
The controller has moved to a separate ros node `carla_ackermann_control` If you have multiple ego-vehicles, just specify the ros parameter `role_name`.
